name: Setup Rust Environment

inputs:
  key:
    description: Cache key
    required: true
  toolchain:
    description: Pass-through to toolchain on actions-rs
    default: stable
    required: false
  components:
    description: Pass-through to components on actions-rs
    required: false

runs:
  using: composite
  steps:
    - name: Remove rustfmt
      run: rm -f ~/.cargo/bin/rustfmt ~/.cargo/bin/cargo-fmt
      shell: bash

    - name: Rustup Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/downloads
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
        key: v5-rustup-${{ runner.os }}

    - name: Install Toolchain
      uses: dtolnay/rust-toolchain@v1
      id: toolchain-install
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - name: Update self
      run: rustup self update || true
      shell: bash

    - name: Update
      run: rustup update || true
      shell: bash

    - name: Build Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/bin/
          target/
        key: |
          v5-${{ inputs.key }}-${{ runner.os }}-${{ inputs.toolchain }}-${{ steps.toolchain-install.outputs.cachekey }}-${{ hashFiles('**/Cargo.toml', 'Cargo.lock') }}
        restore-keys: |
          v5-${{ inputs.key }}-${{ runner.os }}-${{ inputs.toolchain }}-${{ steps.toolchain-install.outputs.cachekey }}-
          v5-${{ inputs.key }}-${{ runner.os }}-${{ inputs.toolchain }}-
