[package]
name = "tzdb-fuzz"
version = "0.0.0"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/tzdb"
description = "… fuzz …"
license = "Apache-2.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
tzdb_data = { path = "../tzdb_data" }

libfuzzer-sys = "0.4"

[[bin]]
name = "tzdb-fuzz-libfuzzer"
path = "bin/libfuzzer.rs"
test = false
doc = false

[workspace]
members = ["."]
