[package]
name = "tzdb"
version = "0.1.0"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/tzdb"
description = "Static time zone information for tz-rs"
license = "Apache-2.0"
keywords = ["date", "time", "timezone", "zone", "calendar"]
categories = ["date-and-time"]
readme = "README.md"
rust-version = "1.57"

[dependencies]
tz-rs = "0.6.0"

# optional dependencies
byte-slice-cast = { version = "1.2.1", optional = true }
document-features = { version = "=0.2.1", optional = true }
iana-time-zone = { version = "0.1.29", optional = true }
phf = { version = "0.10.1", optional = true }

[features]
default = ["by-name", "list", "local"]
## enables [TimeZoneExt::from_db()]
##
by-name = ["phf", "byte-slice-cast"]
## enables [TimeZoneExt::names_in_db()]
##
list = []
## enables [TimeZoneExt::local_from_db()]
##
local = ["by-name", "iana-time-zone"]

# Internal feature, used when generating docs. *You* are not supposed to enable this feature!
docsrs = ["document-features", "default"]

[package.metadata.docs.rs]
features = ["docsrs"]
